### ISSUE TITLE
cnmts.json missing ending

### ISSUE THREAD

**Issue by johnlescault** [blawar/titledb#26]
Hi,
When I download cnmts.json it seems to end at and creates an incomplete json file. Line 1071943 is the last line, and is '"metaEntries"': [], see below

```
        "196608": {
            "contentEntries": [
                {
                    "buildId": "29F4D3D132694C438BA34B6E0ABB26B800000000000000000000000000000000",
                    "ncaId": "de9e2015a1b467e5d8c3719ab331d3f5",
                    "type": 1
                },
                {
                    "ncaId": "3c53199225810db6f524fe270aea5d14",
                    "type": 3
                },
                {
                    "ncaId": "abf6842a2da9f1eebcbc43079fbdebf6",
                    "type": 5
                }
            ],
            "metaEntries": []
```

**Comment by blawar** [comment]
should be fixed now.

**Comment by johnlescault** [comment]
Worked like a charm! Thanks!

**Comment by johnlescault** [comment]
Unfortunately the issue came back. cnmts.json is now ending with:

```
    "0100fe0014200000": {
        "0": {
            "contentEntries": 
```

**Comment by blawar** [comment]
> 

ran out of disk space last week due to that one huge update, I fixed the cnmt file.

**Comment by johnlescault** [comment]
That was fast! Thank you so much!

**Comment by Superpiffer** [comment]
Same problem, cnmts.json ends like this:
![image](https://github.com/blawar/titledb/assets/1334453/5e8e9392-c099-4352-b63e-74dc8cb723c5)

**Comment by blawar** [comment]
its fixed, server ran out of disk space.
